version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=edtech_assistant
      - MYSQL_USER=edtech
      - MYSQL_PASSWORD=edtech123
    volumes:
      - ../docker-data/mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    volumes:
      - ../docker-data/rabbit_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "5540:8001"
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ../docker-data/grafana:/var/lib/grafana
    depends_on:
      - prometheus