apiVersion: v1
kind: Service
metadata:
  name: assignment-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8081
  - name: metrics
    port: 8181
    targetPort: 8181
  selector:
    app: assignment