apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  ports:
    - name: api
      port: 80
      targetPort: 8080
    - name: websocket
      port: 8180
      targetPort: 8180
  selector:
    app: api