apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8084
  - name: metrics
    port: 8184
    targetPort: 8184
  selector:
    app: chat
