apiVersion: v1
kind: Service
metadata:
  name: background-job-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8083
  - name: metrics
    port: 8183
    targetPort: 8183
  selector:
    app: background-job