DROP DATABASE IF EXISTS edtech_assistant_chat;
CREATE DATABASE IF NOT EXISTS edtech_assistant_chat;
USE edtech_assistant_chat;

CREATE TABLE chat_topic (
	id INT AUTO_INCREMENT PRIMARY KEY,
	topic_name VARCHAR(255) NOT NULL DEFAULT 'Untitled',
	account_id INT NOT NULL,
	document_id VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE chat_message (
	id INT AUTO_INCREMENT PRIMARY KEY,
	topic_id INT NOT NULL,
	chat_message TEXT NOT NULL,
	chat_role VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (topic_id) REFERENCES chat_topic(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE chat_file_key (
	id INT AUTO_INCREMENT PRIMARY KEY,
	chat_message_id INT NOT NULL,
    file_name VARCHAR (255) NOT NULL,
	file_type VARCHAR(255) NOT NULL,
    file_code VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (chat_message_id) REFERENCES chat_message(id) ON DELETE CASCADE ON UPDATE CASCADE
);