apiVersion: v1
kind: Service
metadata:
  name: quiz-service
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8082
  - name: ws
    port: 8282
    targetPort: 8282
  - name: metrics
    port: 8182
    targetPort: 8182
  selector:
    app: quiz
